import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        abel: ["Abel", "sans-serif"],
        gilroy: ["Gilroy", "sans-serif"],
      },
      height:{
        headerBig:"4rem",
        headerSmall:"3.5rem"
      },
      fontSize: {
        h1Big: "3.5rem",
        h1Small: "2rem",
        h2Big: "3.8rem",
        h2Small: "2.2rem",
        h3Big: "1.75rem",
        h3Small: "1rem",
        h4Big: "1.3rem",
        h4Small: "1rem",
        h5Big: "1rem",
        h5Small: ".8rem",
        h6Big: "",
        h6Small: "",
        body1Big: ".9rem",
        body1Small: ".7rem",
        body1BoltBig: "",
        body1BoltSmall: "",
        body2Big: "",
        body2Small: "",
        body2BoltBig: "",
        body2BoltSmall: "",
        smallBodyBig: ".7rem",
        smallBodySmall: ".5rem",
        overlineBig: "1.7rem",
        overlineSmall: "1.4rem",
        captionBig: "",
        captionSmall: "",
        menuBig: "",
        menuSmall: "",
        btnBig:".8rem",
        btnSmall:".8rem",
      },
      spacing: {
        // containerTopBig: "7rem",
        // containerTopSmall: "5rem",
        containerSideBig: "5rem",
        containerSideSmall: "1.5rem",
        eightyBig: "5rem",
        eightySmall: "1.5rem",
        fiftySixBig: "3.5rem",
        fiftySixSmall: "1.5rem",
        fortyEightBig:"2.4rem",
        fortyEightSmall:"1.8rem",
        fortyBig: "2rem",
        fortySmall: "1.5rem",
        thirtyTwoBig:"1.6rem",
        thirtyTwoSmall:"1.2rem",
        twentyFourBig:"1.2rem",
        twentyFourSmall:"0.9rem",
        sixteen: "1rem",
      },
    },
  },
  plugins: [],
};

export default config;
